In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

In [2]:
customers_df = pd.DataFrame(data={
    "id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "prenom": ["Jean", "Marie", "Paul", "Sophie", "Luc", "Emma", "Louis", "Chloé", "Hugo", "Léa"],
    "nom": ["Dupont", "Martin", "Durand", "Petit", "Leroy", "Moreau", "Simon", "Laurent", "Michel", "Garcia"],
    "email": [
        "jean.dupont@email.com",
        "marie.martin@email.com",
        "paul.durand@email.com",
        "sophie.petit@email.com",
        "luc.leroy@email.com",
        "emma.moreau@email.com",
        "louis.simon@email.com",
        "chloe.laurent@email.com",
        "hugo.michel@email.com",
        "lea.garcia@email.com"
    ],
    "date_inscription": [
        "2023-01-15",
        "2023-02-20",
        "2023-03-10",
        "2023-04-05",
        "2023-05-18",
        "2023-06-22",
        "2023-07-30",
        "2023-08-14",
        "2023-09-09",
        "2023-10-01"
    ]
}).set_index('id')

customers_df

    prenom      nom                    email date_inscription
id
1     Jean   Dupont    jean.dupont@email.com       2023-01-15
2    Marie   Martin   marie.martin@email.com       2023-02-20
3     Paul   Durand    paul.durand@email.com       2023-03-10
4   Sophie    Petit   sophie.petit@email.com       2023-04-05
5      Luc    Leroy      luc.leroy@email.com       2023-05-18
6     Emma   Moreau    emma.moreau@email.com       2023-06-22
7    Louis    Simon    louis.simon@email.com       2023-07-30
8    Chloé  Laurent  chloe.laurent@email.com       2023-08-14
9     Hugo   Michel    hugo.michel@email.com       2023-09-09
10     Léa   Garcia     lea.garcia@email.com       2023-10-01

In [3]:
products_df = pd.DataFrame(data = {
    "id": list(range(1, 11)),
    "libelle_produit": [
        "Chaussures de randonnée imperméables",
        "Sac à dos 40L",
        "Bâtons de marche télescopiques",
        "Tente 2 places légère",
        "Sac de couchage -5°C",
        "Lampe frontale LED",
        "Gourde isotherme 1L",
        "Matelas de sol gonflable",
        "Veste coupe-vent",
        "GPS de randonnée"
    ],
    "code_produit": [
        "RANDO-CHA-001",
        "RANDO-SAC-002",
        "RANDO-BAT-003",
        "RANDO-TEN-004",
        "RANDO-COU-005",
        "RANDO-LAM-006",
        "RANDO-GOU-007",
        "RANDO-MAT-008",
        "RANDO-VET-009",
        "RANDO-GPS-010"
    ],
    "fournisseur": [
        "Decathlon",
        "The North Face",
        "Black Diamond",
        "Quechua",
        "Millet",
        "Petzl",
        "CamelBak",
        "Therm-a-Rest",
        "Columbia",
        "Garmin"
    ]
}).set_index('id')

products_df

                         libelle_produit   code_produit     fournisseur
id
1   Chaussures de randonnée imperméables  RANDO-CHA-001       Decathlon
2                          Sac à dos 40L  RANDO-SAC-002  The North Face
3         Bâtons de marche télescopiques  RANDO-BAT-003   Black Diamond
4                  Tente 2 places légère  RANDO-TEN-004         Quechua
5                   Sac de couchage -5°C  RANDO-COU-005          Millet
6                     Lampe frontale LED  RANDO-LAM-006           Petzl
7                    Gourde isotherme 1L  RANDO-GOU-007        CamelBak
8               Matelas de sol gonflable  RANDO-MAT-008    Therm-a-Rest
9                       Veste coupe-vent  RANDO-VET-009        Columbia
10                      GPS de randonnée  RANDO-GPS-010          Garmin

In [4]:
nb_ventes = 20

sells_df = pd.DataFrame(data={
    "id": range(1, nb_ventes + 1),
    "client_id": np.random.randint(1, 11, nb_ventes),   # clients 1 à 10
    "produit_id": np.random.randint(1, 11, nb_ventes),  # produits 1 à 10
    "date_achat": pd.to_datetime(
        np.random.choice(pd.date_range("2023-01-01", "2023-12-31"), nb_ventes)
    ),
    "prix_vente": np.round(np.random.uniform(20, 300, nb_ventes), 2)
}).set_index('id')

sells_df

    client_id  produit_id date_achat  prix_vente
id
1           7           5 2023-03-30       28.77
2           4           1 2023-11-12      255.84
3           8          10 2023-01-14      145.93
4           5           6 2023-08-30      130.64
5           7           9 2023-09-22      279.46
6          10           1 2023-12-12      223.64
7           3          10 2023-02-22      111.43
8           7           3 2023-12-06      179.72
9           8           7 2023-04-02      165.83
10          5           4 2023-09-21      289.13
11          4           9 2023-02-04      256.47
12          8           3 2023-07-25      229.25
13          8           5 2023-03-22      171.11
14          3           3 2023-02-19      184.29
15          6           7 2023-12-26      290.27
16          5           5 2023-01-02      189.97
17          2           9 2023-02-23       97.28
18          8           7 2023-04-16      102.96
19          6           2 2023-09-17       66.27
20          2           4 2023-11-06       24.38

In [5]:
def merge_sales_products(sales: pd.DataFrame, products: pd.DataFrame) -> pd.DataFrame:
    return pd.merge(
        left=sales,
        right=products,
        left_on='produit_id',
        right_on='id',
        how='inner'
    )

def merge_sales_customers(customers: pd.DataFrame, sales_with_products: pd.DataFrame) -> pd.DataFrame:
    return pd.merge(
        left=customers,
        right=sales_with_products,
        left_on='id',
        right_on='client_id',
        how='inner'
    )

In [6]:
sales_with_products_df = merge_sales_products(
    sales=sells_df,
    products=products_df
)

flat = merge_sales_customers(
    customers=customers_df,
    sales_with_products=sales_with_products_df
)

flat

,prenom,nom,email,date_inscription,client_id,produit_id,date_achat,prix_vente,libelle_produit,code_produit,fournisseur
0,Marie,Martin,marie.martin@email.com,2023-02-20,2,9,2023-02-23,97.28,Veste coupe-vent,RANDO-VET-009,Columbia
1,Marie,Martin,marie.martin@email.com,2023-02-20,2,4,2023-11-06,24.38,Tente 2 places légère,RANDO-TEN-004,Quechua
2,Paul,Durand,paul.durand@email.com,2023-03-10,3,10,2023-02-22,111.43,GPS de randonnée,RANDO-GPS-010,Garmin
3,Paul,Durand,paul.durand@email.com,2023-03-10,3,3,2023-02-19,184.29,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
4,Sophie,Petit,sophie.petit@email.com,2023-04-05,4,1,2023-11-12,255.84,Chaussures de randonnée imperméables,RANDO-CHA-001,Decathlon
5,Sophie,Petit,sophie.petit@email.com,2023-04-05,4,9,2023-02-04,256.47,Veste coupe-vent,RANDO-VET-009,Columbia
6,Luc,Leroy,luc.leroy@email.com,2023-05-18,5,6,2023-08-30,130.64,Lampe frontale LED,RANDO-LAM-006,Petzl
7,Luc,Leroy,luc.leroy@email.com,2023-05-18,5,4,2023-09-21,289.13,Tente 2 places légère,RANDO-TEN-004,Quechua
8,Luc,Leroy,luc.leroy@email.com,2023-05-18,5,5,2023-01-02,189.97,Sac de couchage -5°C,RANDO-COU-005,Millet
9,Emma,Moreau,emma.moreau@email.com,2023-06-22,6,7,2023-12-26,290.27,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
10,Emma,Moreau,emma.moreau@email.com,2023-06-22,6,2,2023-09-17,66.27,Sac à dos 40L,RANDO-SAC-002,The North Face
11,Louis,Simon,louis.simon@email.com,2023-07-30,7,5,2023-03-30,28.77,Sac de couchage -5°C,RANDO-COU-005,Millet
12,Louis,Simon,louis.simon@email.com,2023-07-30,7,9,2023-09-22,279.46,Veste coupe-vent,RANDO-VET-009,Columbia
13,Louis,Simon,louis.simon@email.com,2023-07-30,7,3,2023-12-06,179.72,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
14,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,10,2023-01-14,145.93,GPS de randonnée,RANDO-GPS-010,Garmin
15,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,7,2023-04-02,165.83,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
16,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,3,2023-07-25,229.25,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
17,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,5,2023-03-22,171.11,Sac de couchage -5°C,RANDO-COU-005,Millet
18,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,7,2023-04-16,102.96,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
19,Léa,Garcia,lea.garcia@email.com,2023-10-01,10,1,2023-12-12,223.64,Chaussures de randonnée imperméables,RANDO-CHA-001,Decathlon

In [7]:
def get_customers_buys_stats(customers: pd.DataFrame, flat: pd.DataFrame) -> pd.DataFrame:
    return pd.merge(
        left=customers,
        right=flat.groupby("client_id").agg(
            nb_ventes=("produit_id", "count"),
            total_depenses=("prix_vente", "sum")
        ),
        left_on='id',
        right_on='client_id',
        how='inner'
    )

In [8]:
customers_stats_df = get_customers_buys_stats(
    customers=customers_df,
    flat=flat
)

customers_stats_df

,prenom,nom,email,date_inscription,nb_ventes,total_depenses
0,Marie,Martin,marie.martin@email.com,2023-02-20,2,121.66
1,Paul,Durand,paul.durand@email.com,2023-03-10,2,295.72
2,Sophie,Petit,sophie.petit@email.com,2023-04-05,2,512.31
3,Luc,Leroy,luc.leroy@email.com,2023-05-18,3,609.74
4,Emma,Moreau,emma.moreau@email.com,2023-06-22,2,356.54
5,Louis,Simon,louis.simon@email.com,2023-07-30,3,487.95
6,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,5,815.08
7,Léa,Garcia,lea.garcia@email.com,2023-10-01,1,223.64

In [9]:
class DataFramesManager():

    def __init__(self) -> None:
        self.dataframes: dict[str, pd.DataFrame] = dict()
        self.records: list[list[str]] = []

    def __getitem__(self, key) -> pd.DataFrame:
        return self.dataframes[key]
    
    def __setitem__(self, key, value) -> None:
        self.dataframes[key] = value
        self.records.append([key])

    def __str__(self) -> str:
        return ', '.join(self.dataframes.keys())
    
    def __repr__(self) -> str:
        return self.__str__()
    
    def inject_kwargs(self, dataframes: list[str]) -> dict[str, pd.DataFrame]:
        self.records.append(dataframes)
        return {key: self.dataframes[key] for key in dataframes if key in self.dataframes.keys()}
    
    def resolve(self, func):
        pass

dfm = DataFramesManager()

In [10]:
dfm['sales'] = sells_df
dfm['products'] = products_df
dfm['customers'] = customers_df

dfm

sales, products, customers

In [11]:
dfm['sales_with_products'] = merge_sales_products(**dfm.inject_kwargs(['sales', 'products']))
dfm['sales_with_products']

,client_id,produit_id,date_achat,prix_vente,libelle_produit,code_produit,fournisseur
0,7,5,2023-03-30,28.77,Sac de couchage -5°C,RANDO-COU-005,Millet
1,4,1,2023-11-12,255.84,Chaussures de randonnée imperméables,RANDO-CHA-001,Decathlon
2,8,10,2023-01-14,145.93,GPS de randonnée,RANDO-GPS-010,Garmin
3,5,6,2023-08-30,130.64,Lampe frontale LED,RANDO-LAM-006,Petzl
4,7,9,2023-09-22,279.46,Veste coupe-vent,RANDO-VET-009,Columbia
5,10,1,2023-12-12,223.64,Chaussures de randonnée imperméables,RANDO-CHA-001,Decathlon
6,3,10,2023-02-22,111.43,GPS de randonnée,RANDO-GPS-010,Garmin
7,7,3,2023-12-06,179.72,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
8,8,7,2023-04-02,165.83,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
9,5,4,2023-09-21,289.13,Tente 2 places légère,RANDO-TEN-004,Quechua
10,4,9,2023-02-04,256.47,Veste coupe-vent,RANDO-VET-009,Columbia
11,8,3,2023-07-25,229.25,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
12,8,5,2023-03-22,171.11,Sac de couchage -5°C,RANDO-COU-005,Millet
13,3,3,2023-02-19,184.29,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
14,6,7,2023-12-26,290.27,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
15,5,5,2023-01-02,189.97,Sac de couchage -5°C,RANDO-COU-005,Millet
16,2,9,2023-02-23,97.28,Veste coupe-vent,RANDO-VET-009,Columbia
17,8,7,2023-04-16,102.96,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
18,6,2,2023-09-17,66.27,Sac à dos 40L,RANDO-SAC-002,The North Face
19,2,4,2023-11-06,24.38,Tente 2 places légère,RANDO-TEN-004,Quechua

In [12]:
dfm['flat'] = merge_sales_customers(**dfm.inject_kwargs(['sales_with_products', 'customers']))
dfm['flat']

,prenom,nom,email,date_inscription,client_id,produit_id,date_achat,prix_vente,libelle_produit,code_produit,fournisseur
0,Marie,Martin,marie.martin@email.com,2023-02-20,2,9,2023-02-23,97.28,Veste coupe-vent,RANDO-VET-009,Columbia
1,Marie,Martin,marie.martin@email.com,2023-02-20,2,4,2023-11-06,24.38,Tente 2 places légère,RANDO-TEN-004,Quechua
2,Paul,Durand,paul.durand@email.com,2023-03-10,3,10,2023-02-22,111.43,GPS de randonnée,RANDO-GPS-010,Garmin
3,Paul,Durand,paul.durand@email.com,2023-03-10,3,3,2023-02-19,184.29,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
4,Sophie,Petit,sophie.petit@email.com,2023-04-05,4,1,2023-11-12,255.84,Chaussures de randonnée imperméables,RANDO-CHA-001,Decathlon
5,Sophie,Petit,sophie.petit@email.com,2023-04-05,4,9,2023-02-04,256.47,Veste coupe-vent,RANDO-VET-009,Columbia
6,Luc,Leroy,luc.leroy@email.com,2023-05-18,5,6,2023-08-30,130.64,Lampe frontale LED,RANDO-LAM-006,Petzl
7,Luc,Leroy,luc.leroy@email.com,2023-05-18,5,4,2023-09-21,289.13,Tente 2 places légère,RANDO-TEN-004,Quechua
8,Luc,Leroy,luc.leroy@email.com,2023-05-18,5,5,2023-01-02,189.97,Sac de couchage -5°C,RANDO-COU-005,Millet
9,Emma,Moreau,emma.moreau@email.com,2023-06-22,6,7,2023-12-26,290.27,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
10,Emma,Moreau,emma.moreau@email.com,2023-06-22,6,2,2023-09-17,66.27,Sac à dos 40L,RANDO-SAC-002,The North Face
11,Louis,Simon,louis.simon@email.com,2023-07-30,7,5,2023-03-30,28.77,Sac de couchage -5°C,RANDO-COU-005,Millet
12,Louis,Simon,louis.simon@email.com,2023-07-30,7,9,2023-09-22,279.46,Veste coupe-vent,RANDO-VET-009,Columbia
13,Louis,Simon,louis.simon@email.com,2023-07-30,7,3,2023-12-06,179.72,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
14,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,10,2023-01-14,145.93,GPS de randonnée,RANDO-GPS-010,Garmin
15,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,7,2023-04-02,165.83,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
16,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,3,2023-07-25,229.25,Bâtons de marche télescopiques,RANDO-BAT-003,Black Diamond
17,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,5,2023-03-22,171.11,Sac de couchage -5°C,RANDO-COU-005,Millet
18,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,8,7,2023-04-16,102.96,Gourde isotherme 1L,RANDO-GOU-007,CamelBak
19,Léa,Garcia,lea.garcia@email.com,2023-10-01,10,1,2023-12-12,223.64,Chaussures de randonnée imperméables,RANDO-CHA-001,Decathlon

In [13]:
dfm['customers_stats'] = get_customers_buys_stats(**dfm.inject_kwargs(['flat', 'customers']))
dfm['customers_stats']

,prenom,nom,email,date_inscription,nb_ventes,total_depenses
0,Marie,Martin,marie.martin@email.com,2023-02-20,2,121.66
1,Paul,Durand,paul.durand@email.com,2023-03-10,2,295.72
2,Sophie,Petit,sophie.petit@email.com,2023-04-05,2,512.31
3,Luc,Leroy,luc.leroy@email.com,2023-05-18,3,609.74
4,Emma,Moreau,emma.moreau@email.com,2023-06-22,2,356.54
5,Louis,Simon,louis.simon@email.com,2023-07-30,3,487.95
6,Chloé,Laurent,chloe.laurent@email.com,2023-08-14,5,815.08
7,Léa,Garcia,lea.garcia@email.com,2023-10-01,1,223.64

In [14]:
dfm.records

[['sales'],
 ['products'],
 ['customers'],
 ['sales', 'products'],
 ['sales_with_products'],
 ['sales_with_products', 'customers'],
 ['flat'],
 ['flat', 'customers'],
 ['customers_stats']]

In [39]:
from IPython.display import HTML
import base64

def render_html_in_ifram(html: str) -> HTML:
    encoded = base64.b64encode(html.encode()).decode()
    page = f'<iframe src="data:text/html;base64,{encoded}" width="100%" height="600px"></iframe>'
    return HTML(page)

In [40]:
import json
from pyvis.network import Network


net = Network(directed=True)

options = {
    "layout": {
        "hierarchical": {
            "enabled": True,
            "direction": "UD",
            "sortMethod": "directed"
    }
  },
  "physics": {
    "enabled": True
  }
}

net.set_options(json.dumps(options))

level = 0
for idx, group in enumerate(dfm.records):
    if len(group) == 1:
        net.add_node(
            n_id=group[0],
            #color='blue',
            level=level
        )
    else:
        level += 1

for idx, group in enumerate(dfm.records):
    if len(group) > 1:
        for item in group:
            net.add_edge(
                source=item,
                to=dfm.records[idx+1][0],
                #label='coucou'
            )

render_html_in_ifram(net.generate_html())

/Users/christux/Programmation/Notebooks/.venv/lib/python3.12/site-packages/IPython/core/display.py:474: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")